<?php

namespace A2ZWeb\Affiliate\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class PartnerEligibleToApply extends Notification
{
    use Queueable;

    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject(__('You can now join our Affiliate Program 🎉'))
            ->greeting(__('Great news!'))
            ->line(__('You have referred enough new users to apply for our Affiliate Program.'))
            ->line(__('As an affiliate partner, you earn a recurring share of the revenue generated by every paying customer you refer.'))
            ->action(__('Apply now'), url(config('affiliate.routes.prefix', 'dashboard/affiliate')))
            ->line(__('On the dashboard you can review the program terms, accept them, and provide your payout details so you are ready the moment one of your referrals starts paying.'));
    }
}
