<?php

namespace A2ZWeb\Affiliate\Contracts;

interface RevenueResolver
{
    /**
     * Return revenue (in minor units / cents) generated by the given user
     * during the specified calendar month. The hosting application is
     * responsible for ensuring this number reflects realised revenue —
     * the package will only call this for fully closed past months.
     */
    public function revenueForUserInMonth(int $userId, int $year, int $month): int;

    /**
     * Return revenue (in minor units / cents) generated by the given user
     * from the start of the current month up to "now". Used by the partner
     * dashboard to display an in-progress current-month estimate alongside
     * fully-closed historical periods. Implementations may return 0 when no
     * live data source is available — the dashboard simply shows zero.
     */
    public function currentMonthRunningRevenueCents(int $userId): int;
}
