<?php

namespace A2ZWeb\Affiliate\Contracts;

interface RevenueResolver
{
    /**
     * Return revenue (in minor units / cents) generated by the given user
     * during the specified calendar month. The hosting application is
     * responsible for ensuring this number reflects realised revenue —
     * the package will only call this for fully closed past months.
     */
    public function revenueForUserInMonth(int $userId, int $year, int $month): int;
}
